//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 06:32:15 PM EST 
//

package com.tntdjs.midi.controllers.data.config;

import javax.xml.bind.annotation.XmlRegistry;

import com.tntdjs.midi.controllers.data.config.objects.ButtonSet;
import com.tntdjs.midi.controllers.data.config.objects.MidiButton;
import com.tntdjs.midi.controllers.data.config.objects.MidiDevices;
import com.tntdjs.midi.controllers.data.config.objects.PotentiometerGroups;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programmatically construct new instances of
 * the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the
 * binding of schema type definitions, element declarations and model groups.
 * Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link MidiDevices }
	 * 
	 */
	public MidiDevices createMidiDevices() {
		return new MidiDevices();
	}

	/**
	 * Create an instance of {@link MidiDevices.Device }
	 * 
	 */
	public MidiDevices.Device createMidiDevicesDevice() {
		return new MidiDevices.Device();
	}

	/**
	 * Create an instance of {@link MidiDevices.Device.ButtonGroups }
	 * 
	 */
	public MidiDevices.Device.ButtonGroups createMidiDevicesDeviceButtonGroups() {
		return new MidiDevices.Device.ButtonGroups();
	}

	/**
	 * Create an instance of {@link MidiDevices.Device.ButtonGroups.ButtonSet }
	 * 
	 */
	public ButtonSet createMidiDevicesDeviceButtonGroupsButtonSet() {
		return new ButtonSet();
	}

	/**
	 * Create an instance of {@link MidiDevices.Device.PotentiometerGroups }
	 * 
	 */
	public PotentiometerGroups createMidiDevicesDevicePotentiometerGroups() {
		return new PotentiometerGroups();
	}

	/**
	 * Create an instance of
	 * {@link MidiDevices.Device.ButtonGroups.ButtonSet.MidiButton }
	 * 
	 */
	public MidiButton createMidiDevicesDeviceButtonGroupsButtonSetMidiButton() {
		return new MidiButton();
	}

}
